### ISSUE TITLE
Problem with snippet

### ISSUE THREAD

**Issue by ghost** [deqoda/deqoda#1]
Hello, I have a small problem when I trying to add icon to tab..
``$("head").append("
");

This is example on your website: [https://www.deqoda.com/snippets/add-icon-on-tab/](url)

**Comment by deqoda** [comment]
Hello, you can easily add icon, text, etc, here is a example:

`$(document).ready(function(){
    $("#button").click(function(){
        $("ol").append("<li>Appended item</li>");
    });
});`

Sure you'll have to have html with class and id (look in yQuery code), 
HTML
<ol>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ol>

<button id="button">Append text</button>

**Comment by ghost** [comment]
Oh nice, thank you :-).
